// Generated by CoffeeScript 1.3.1
(function() {

  $(function() {
    return twttr.anywhere(function(T) {
      var checkStatus, loginBtn, logoutBtn;
      logoutBtn = $(".twitter.logout");
      loginBtn = $(".twitter.login");
      checkStatus = function() {
        var currentUser, screenName;
        if (T.isConnected()) {
          currentUser = T.currentUser;
          logoutBtn.show();
          loginBtn.hide();
          screenName = currentUser.data('screen_name');
          return $.ajax({
            url: "http://api.twitter.com/1/users/lookup.json",
            data: {
              screen_name: screenName
            },
            dataType: "jsonp",
            success: function(data) {
              console.log("twitter api results");
              return console.log(data);
            }
          });
        } else {
          loginBtn.show();
          return logoutBtn.hide();
        }
      };
      checkStatus();
      T.bind("authComplete", function(e, user) {
        console.log("successfully authentication");
        return checkStatus();
      });
      T.bind("signOut", function(e) {
        console.log("user logged out");
        return checkStatus();
      });
      loginBtn.click(function(evt) {
        evt.preventDefault();
        return T.signIn();
      });
      return logoutBtn.click(function(evt) {
        evt.preventDefault();
        return twttr.anywhere.signOut();
      });
    });
  });

}).call(this);
