// Generated by CoffeeScript 1.3.1
(function() {

  window.fbAsyncInit = function() {
    FB.init({
      appId: '152191558175911',
      status: true,
      cookie: true,
      xfbml: true
    });
    return $(function() {
      var checkStatus, loginBtn, logoutBtn;
      loginBtn = $(".facebook .login");
      logoutBtn = $(".facebook .logout");
      loginBtn.click(function(evt) {
        evt.preventDefault();
        return FB.login();
      });
      logoutBtn.click(function(evt) {
        evt.preventDefault();
        return FB.logout();
      });
      checkStatus = function(response) {
        if (response.authResponse) {
          return FB.api("/me", function(me) {
            console.log("Hi " + me.name + "!");
            loginBtn.hide();
            return logoutBtn.show();
          });
        } else {
          loginBtn.show();
          return logoutBtn.hide();
        }
      };
      return FB.Event.subscribe('auth.statusChange', function(response) {
        return checkStatus(response);
      });
    });
  };

  (function(d) {
    var id, js, ref;
    id = 'facebook-jssdk';
    ref = d.getElementsByTagName('script')[0];
    if (d.getElementById(id)) {
      return;
    }
    js = d.createElement('script');
    js.id = id;
    js.async = true;
    js.src = "//connect.facebook.net/en_US/all.js";
    return ref.parentNode.insertBefore(js, ref);
  })(document);

}).call(this);
